### ISSUE TITLE
Dependency on pry listed in :test section of Gemfile

### ISSUE THREAD

**Issue by sagepe** [everypolitician/legislative-explorer#7]
# Problem

The dependency on `pry` is listed in the `:test` section of the `Gemfile`, but appears to be required in normal use so when deploying without the dependencies listed in `:test` the application won't run - for example, Heroku by default sets `BUNDLE_WITHOUT=development,test`.

# Proposed Solution

Move `pry` to the main section of the `Gemfile`.

**Comment by sagepe** [comment]
Just to note, the current Heroku deployment sets `BUNDLE_WITHOUT=development`.

**Comment by henare** [comment]
Thanks for raising this @sagepe 🙌 

Moving `pry` to the main section of the `Gemfile` would make it available in production and it's good practice to avoid that. There's a couple of other options we could consider:

* Make all those `require`s conditional on the environment so pry is only loaded in test
* Remove the `require 'pry'` lines and allow the developer to manually insert them when using pry

Because this gem is only in the `:test` section of our `Gemfile` I'm guessing that it is used by a developer when they want a REPL while debugging tests. Since they already need to insert `binding.pry` to get their REPL I don't think it's much of a stretch to instead include `require 'pry'; binding.pry`.

I'll open a PR suggesting we remove the `require`s.

**Comment by henare** [comment]
In fact, the `test_helper` has that `require` so that's all that's needed for getting a REPL in test.

I'm not sure how those other `require`s help given `pry` shouldn't be available in development.

I think that makes this an easy decision.

**Comment by tmtmtmtm** [comment]
Yep, I think simply removing them from the production code is best. 👍

**Comment by henare** [comment]
>Just to note, the current Heroku deployment sets BUNDLE_WITHOUT=development.

I've switched this back to the default, `heroku config:set BUNDLE_WITHOUT=development,test`, then deployed and checked everything's still working.

Interestingly I note that `pry` is still part of our deployed bundle so `¯\_(ツ)_/¯`.

**Comment by sagepe** [comment]
Odd, it definitely failed due to missing `pry` when I first deployed it from my fork in my account. As you say, `¯\_(ツ)_/¯`!
